### ISSUE TITLE
demo运行的问题

### ISSUE THREAD

**Issue by czj942650673** [aliyun/NeWCRFs#12]
![~Q9B$Q I {RMADO8GO{@MG](https://user-images.githubusercontent.com/72180668/173180761-e6c45496-fa3e-4a2b-bc85-ee6c39287f7f.png)
请问一下您遇到过这个问题吗

**Comment by weihaosky** [comment]
可能视频加载的有问题？

**Comment by czj942650673** [comment]
解决了 谢谢您



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Weihao ***@***.***&gt;; 
发送时间: 2022年6月14日(星期二) 上午10:59
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [aliyun/NeWCRFs] demo运行的问题 (Issue #12)





 
可能视频加载的有问题？

**Comment by fanshixiong** [comment]
@czj942650673  你好，请问怎么解决的呢？
