### ISSUE TITLE
About Computation resources

### ISSUE THREAD

**Issue by jpark1031** [aliyun/NeWCRFs#14]
Hi, 
It seems you use multiple GPUs for the training.
Can you answer how many GPUs("Nvidia  GTX  2080  Ti  GPUs." mentioned in your paper) did you use for training?

Thanks.

**Comment by zcliu457** [comment]
How many 2080Ti GPUs have you tried in your experiments?

**Comment by weihaosky** [comment]
Usually I use 4 or 8 2080Ti
