### ISSUE TITLE
about backbone

### ISSUE THREAD

**Issue by Shawn9257** [aliyun/NeWCRFs#15]
Hi, Thanks for your great job.
I am trying to run this code on my datasets. But I don't understand what should I do one the backbone link. Could you give me some lead?

**Comment by weihaosky** [comment]
Follow the readme and download the backbone weight file from that link

**Comment by Shawn9257** [comment]
Thanks for your reply. And I have finish download this backbone. 
Now I am trying to train this network with new datasets. And after I run the training, the output is like:model-1000-best_silog_15.45043 should I change this file as a .pth file or others?

**Comment by weihaosky** [comment]
No need. The suffix doesn't matter
