### ISSUE TITLE
pretrained swin-L model and loaded state dict do not match exactly

### ISSUE THREAD

**Issue by RuijieZhu94** [aliyun/NeWCRFs#16]
Here is the output:
===============
Load encoder backbone from: model_zoo/swin_transformer/swin_large_patch4_window7_224_22k.pth
The model and loaded state dict do not match exactly

unexpected key in source state_dict: norm.weight, norm.bias, head.weight, head.bias, layers.0.blocks.1.attn_mask, layers.1.blocks.1.attn_mask, layers.2.blocks.1.attn_mask, layers.2.blocks.3.attn_mask, layers.2.blocks.5.attn_mask, layers.2.blocks.7.attn_mask, layers.2.blocks.9.attn_mask, layers.2.blocks.11.attn_mask, layers.2.blocks.13.attn_mask, layers.2.blocks.15.attn_mask, layers.2.blocks.17.attn_mask

missing keys in source state_dict: norm0.weight, norm0.bias, norm1.weight, norm1.bias, norm2.weight, norm2.bias, norm3.weight, norm3.bias
================
It seems that the pretrained swin-L model and the source state dict do not match.

**Comment by weihaosky** [comment]
This is normal. There are some differences between the original backbone and the one in our model.
