### ISSUE TITLE
Eval result

### ISSUE THREAD

**Issue by Jason-YJ** [aliyun/NeWCRFs#19]
那个我跟着装了这边的库，跟着BTS那边首页的readme下载了NYU和KITTI，KITTI好像只有GT所以没办法用你这边的eval，然而我NYU直接跑那个eval出来的结果和你这边readme给的数据以及论文数据差距很大，我跑"python newcrfs/eval.py configs/arguments_eval_nyu.txt"的结果大概如下：
![image](https://user-images.githubusercontent.com/71368398/185185291-7eea8b1b-67e4-4f36-849b-8a79d684b2b6.png)
想问一下是什么原因，我检查了一下数据集应该是匹配的

Well, I downloaded NYU and Kitti follow the readme on the front page of BTS. It seems that Kitti only has GT, so I can't use your eval code to test. However, the results of NYU dataset running the eval code differ greatly from the data given by your readme and the paper data. My result when running "python newcrfs/eval.py configs/arguments_eval_nyu.txt" is like following:
![image](https://user-images.githubusercontent.com/71368398/185185291-7eea8b1b-67e4-4f36-849b-8a79d684b2b6.png)
I wonder why cause I checked that the data set is matched.

**Comment by weihaosky** [comment]
这个结果看起来是完全错的，应该还是哪里弄错了，数据没匹配上

**Comment by flowerdance77** [comment]
kitti数据集没法eval吗？我跑的都是nan
<img width="570" alt="075e9e7952c9c5ff24f55c3e1e299a9" src="https://user-images.githubusercontent.com/62199140/207598401-fe2894a7-28ce-48f6-8bcd-140f199e7e98.png">
