### ISSUE TITLE
About GPU Memory requirements for training

### ISSUE THREAD

**Issue by DuoAp** [aliyun/NeWCRFs#21]
Hello, I configured the environment with reference to the information in the readme.md file. But it keeps getting the error "CUDA out of memory"

_RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 6.00 GiB total capacity; 4.92 GiB already allocated; 0 bytes free; 5.37 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF_

_RuntimeError: HIP out of memory. Tried to allocate 54.00 MiB (GPU 0; 15.98 GiB total capacity; 14.39 GiB already allocated; 17179869183.78 GiB free; 14.94 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_HIP_ALLOC_CONF_

**Comment by weihaosky** [comment]
There is a similar issue. #8 
It seems for some GPUs there would be a memory leak from `dist.new_group`
