### ISSUE TITLE
Please provide complete and correct requirements

### ISSUE THREAD

**Issue by Alexdruso** [aliyun/NeWCRFs#23]
Hello, 

I am trying to reproduce the results of your paper and I wanted first to fiddle with demo.py. 
However, I am stuck at the requirements. First of all, the commands you provide do not install pytorch and torchvision in their GPU versions and seem to cause a segfault later on in the process when importing torchvision.
Moreover, demo.py requires scipy, pyside2, opengl, and scikit-image, which are not listed in the requirements.

If I manage to fix my error, I can open a PR with the necessary changes, but I would be extremely grateful if you provided a complete and correct requirements.txt anyway 😄

**Comment by weihaosky** [comment]
I can install the PyTorch with the provided commands. Different systems with different Nvidia driver may need different commands. But installing PyTorch should be quite easy.
The requirements are only for training and testing, not for the demo.
