### ISSUE TITLE
In what units is the result returned?

### ISSUE THREAD

**Issue by denred0** [aliyun/NeWCRFs#26]
Sorry for the stupid question, but I can't figure out what units the result is in.

```
    with torch.no_grad():
        for _, sample in enumerate(tqdm(dataloader.data)):
            image = Variable(sample['image'].cuda())
            # Predict
            depth_est = model(image)
```
[[3.6550407 3.6550407 3.461664  ... 3.2897868 3.4753633 3.4753633],...

I think it's the distance meters for each pixel from the camera, but I'm not sure.

**Comment by weihaosky** [comment]
The unit is in meters.
