### ISSUE TITLE
test on kitti

### ISSUE THREAD

**Issue by jiushidunduna** [aliyun/NeWCRFs#27]
RuntimeError: shape '[1, 7, 7, 23, 7, 256]' is invalid for input of size 2060800

When I test on the kitti dataset, I can't get the output depth map, and the run reports an error as above.Thank you!!!

**Comment by 6leet** [comment]
Hi,  I'm facing the same issue also, do you have any conclusion?  Thanks!

**Comment by northagain** [comment]
The test is defulted used for NYU dataset, therefore u should:
Make sure that args.input_height, width is set to 352,1216.
Use --do_kb_crop to get the right shape.

**Comment by DuoAp** [comment]
> The test is defulted used for NYU dataset, therefore u should: Make sure that args.input_height, width is set to 352,1216. Use --do_kb_crop to get the right shape.

Thank you for your suggestion, I encountered the same problem. However, I found that the size of the images in my KITTI dataset is 375*1242. Why is that? How should I set it?
