### ISSUE TITLE
预训练模型为啥这么大，1G

### ISSUE THREAD

**Issue by jxncyym** [aliyun/NeWCRFs#29]
是不是单目深度估计的模型都很大，差不多都1-2G?为啥没有像其他视觉任务那样，模型那么小？单目深度估计的模型可以用比较小的模型吗？还是因为比较小的模型效果不是很好？

**Comment by weihaosky** [comment]
可以用小模型，效果会相应下降一点

**Comment by hutingz** [comment]
> 是不是单目深度估计的模型都很大，差不多都1-2G?为啥没有像其他视觉任务那样，模型那么小？单目深度估计的模型可以用比较小的模型吗？还是因为比较小的模型效果不是很好？

请问，你复现的结果怎么样

**Comment by XuWink** [comment]
有人复现成功了吗，想请教一下

**Comment by XuWink** [comment]
> > 是不是单目深度估计的模型都很大，差不多都1-2G?为啥没有像其他视觉任务那样，模型那么小？单目深度估计的模型可以用比较小的模型吗？还是因为比较小的模型效果不是很好？
> 
> 请问，你复现的结果怎么样

有结果吗？

**Comment by hutingz** [comment]
我并没有复现出来，抱歉不能帮助你。


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年5月29日(周一) 晚上9:56
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [aliyun/NeWCRFs] 预训练模型为啥这么大，1G (Issue #29)




   
是不是单目深度估计的模型都很大，差不多都1-2G?为啥没有像其他视觉任务那样，模型那么小？单目深度估计的模型可以用比较小的模型吗？还是因为比较小的模型效果不是很好？
  
请问，你复现的结果怎么样
  
有结果吗？
 
&mdash;
