### ISSUE TITLE
Data preparation

### ISSUE THREAD

**Issue by YuhsiHu** [aliyun/NeWCRFs#3]
Thank you for your great work!
I followed the README in bts but the files are not correct:
`
FileNotFoundError: [Errno 2] No such file or directory: '/home/hyx/dataset/newcrfs/dataset/nyu_depth_v2/official_splits/train/dining_room_0031/rgb_00073.jpg'
`
because there is no number **00XX** in folders' name and not many images in folders.
How can I download the correct NYU dataset to meet the requirements of your code?
Thank you for your time!

**Comment by SuperBigBrother** [comment]
me too, but for kitti datasets

**Comment by SuperBigBrother** [comment]
I'm using kitti_raw to train but, emmm, it seems the depth_gt files needed are not in my folder

**Comment by weihaosky** [comment]
> Thank you for your great work! I followed the README in bts but the files are not correct: `FileNotFoundError: [Errno 2] No such file or directory: '/home/hyx/dataset/newcrfs/dataset/nyu_depth_v2/official_splits/train/dining_room_0031/rgb_00073.jpg'` because there is no number **00XX** in folders' name and not many images in folders. How can I download the correct NYU dataset to meet the requirements of your code? Thank you for your time!

The training data is not official_splits/train. You can download the synchronized raw NYUv2 data from [here](https://virutalbuy-public.oss-cn-hangzhou.aliyuncs.com/share/newcrfs/datasets/nyu/sync.zip)

**Comment by weihaosky** [comment]
> I'm using kitti_raw to train but, emmm, it seems the depth_gt files needed are not in my folder

The kitti dataset should be quite standard. You can download from the official website http://www.cvlibs.net/datasets/kitti/eval_depth.php?benchmark=depth_prediction

**Comment by SuperBigBrother** [comment]
> > I'm using kitti_raw to train but, emmm, it seems the depth_gt files needed are not in my folder
> 
> The kitti dataset should be quite standard. You can download from the official website http://www.cvlibs.net/datasets/kitti/eval_depth.php?benchmark=depth_prediction

OK I'm going to try again

**Comment by SuperBigBrother** [comment]
> > I'm using kitti_raw to train but, emmm, it seems the depth_gt files needed are not in my folder
> 
> The kitti dataset should be quite standard. You can download from the official website http://www.cvlibs.net/datasets/kitti/eval_depth.php?benchmark=depth_prediction

Thanks a lot, your work is really outstanding and it seems perform excellence even with fisheye images. The only thing i want is to compress the model, is there any advice?

**Comment by YuhsiHu** [comment]
> > Thank you for your great work! I followed the README in bts but the files are not correct: `FileNotFoundError: [Errno 2] No such file or directory: '/home/hyx/dataset/newcrfs/dataset/nyu_depth_v2/official_splits/train/dining_room_0031/rgb_00073.jpg'` because there is no number **00XX** in folders' name and not many images in folders. How can I download the correct NYU dataset to meet the requirements of your code? Thank you for your time!
> 
> The training data is not official_splits/train. You can download the synchronized raw NYUv2 data from [here](https://virutalbuy-public.oss-cn-hangzhou.aliyuncs.com/share/newcrfs/datasets/nyu/sync.zip)

Thank you for your reply! I have downloaded the sync folder. What should I do? How to split train/valid/test data and set data path?

**Comment by weihaosky** [comment]
> > > I'm using kitti_raw to train but, emmm, it seems the depth_gt files needed are not in my folder
> > 
> > 
> > The kitti dataset should be quite standard. You can download from the official website http://www.cvlibs.net/datasets/kitti/eval_depth.php?benchmark=depth_prediction
> 
> Thanks a lot, your work is really outstanding and it seems perform excellence even with fisheye images. The only thing i want is to compress the model, is there any advice?

You can consider using a smaller backbone or reducing the input size

**Comment by weihaosky** [comment]
> > > Thank you for your great work! I followed the README in bts but the files are not correct: `FileNotFoundError: [Errno 2] No such file or directory: '/home/hyx/dataset/newcrfs/dataset/nyu_depth_v2/official_splits/train/dining_room_0031/rgb_00073.jpg'` because there is no number **00XX** in folders' name and not many images in folders. How can I download the correct NYU dataset to meet the requirements of your code? Thank you for your time!
> > 
> > 
> > The training data is not official_splits/train. You can download the synchronized raw NYUv2 data from [here](https://virutalbuy-public.oss-cn-hangzhou.aliyuncs.com/share/newcrfs/datasets/nyu/sync.zip)
> 
> Thank you for your reply! I have downloaded the sync folder. What should I do? How to split train/valid/test data and set data path?

You can follow the config file. "sync" folder is used for training and official_splits/test is used for testing

**Comment by Tord-Zhang** [comment]
@weihaosky Hi，I don't see the "official_splits/test" folder ? Where should I download it ? Thanks

**Comment by markkua** [comment]
Thank you for your great work and the raw NYUv2 data for training. 
I'm wondering if it possible to share your **preprocessing script** for the synchronized raw data as well. It would be super helpful for me to understand the data.
