### ISSUE TITLE
eval_kitti

### ISSUE THREAD

**Issue by flowerdance77** [aliyun/NeWCRFs#33]
想问下kitti数据集是无法用eval？我跑出来的结果是这样的
<img width="570" alt="075e9e7952c9c5ff24f55c3e1e299a9" src="https://user-images.githubusercontent.com/62199140/207599457-0e77a054-ce95-4296-a657-2e26ad730ef0.png">

**Comment by weihaosky** [comment]
可以的，可能你哪里设置错了
