### ISSUE TITLE
How to train on my own data

### ISSUE THREAD

**Issue by wjlszhang** [aliyun/NeWCRFs#34]
Hi, @weihaosky 

Excellent work!  

And I'd like to train on my own data for my specific scenario,  would you please guide how to organize the data?
I saw the config file for training nyu as  below, I understood "rgb" is the color image, "depth" should be the depth file, but what's the difference between the two "depth" files, sync_depth_xxx.png vs sync_depth_dense_xxx.png?  
(bedroom_0130/rgb_00014.jpg bedroom_0130/sync_depth_00014.png bedroom_0130/dense/sync_depth_dense_00014.png)

Thank you so much!

**Comment by weihaosky** [comment]
"sync_depth_xxx.png" is the original depth obtained from the sensor. The depth values are missing in some places.
"sync_depth_dense_xxx.png" is the depth map where the missing depths are complemented.
You can use either of them.
