### ISSUE TITLE
Synchronized raw NYUv2 data issue

### ISSUE THREAD

**Issue by jwyao1997** [aliyun/NeWCRFs#37]
Hi Weihao,

Thank you so much for your excellent work. I have a question about NYUv2 training dataset you provided in #3 . Does them include extrinct parameter for each image? If not, do you know how to generate/find extrinct parameter for this training dataset?

Thank you so much for your help!

**Comment by weihaosky** [comment]
The NYUv2 dataset includes the extinct parameter for each image.

**Comment by jwyao1997** [comment]
I know the NYUv2 labeled dataset (1449 images in total) include the extinct parameter for each image, but for synchronized raw NYUv2 dataset(https://virutalbuy-public.oss-cn-hangzhou.aliyuncs.com/share/newcrfs/datasets/nyu/sync.zip, 30k+ images in total), do you know how to generate/find extrinct parameter for each image?

**Comment by weihaosky** [comment]
The provided data does not include the camera poses. If you need the camera poses, you could regenerate the images and poses from the raw NYUv2 data.

**Comment by jwyao1997** [comment]
Thanks a lot. I noticed the offical toolbox didn't provide a script to generate the images and poses from the raw NYUv2 data, do you know how to generate them?

**Comment by weihaosky** [comment]
I remember the official toolbox could generate the syncronized images and poses.

**Comment by markkua** [comment]
Thank you for your great work and the raw NYUv2 data for training.
I'm wondering if it possible to share your preprocessing script for the synchronized raw data as well. It would be super helpful.
