### ISSUE TITLE
RuntimeError: shape '[1, 20, 7, 35, 7, 256]' is invalid for input of size 8843520

### ISSUE THREAD

**Issue by kingoo123** [aliyun/NeWCRFs#4]
Hi,I'm trying to test on my own test set, but the following issues arise and I would like to ask you how to fix them
The environment used is as follows：
python 3.8
cuda 10.1
pytorch 1.8.1
mmcv 1.4.8
![image](https://user-images.githubusercontent.com/30140950/163667933-c8d87150-3269-4fe7-8eae-6c06989e277f.png)

**Comment by weihaosky** [comment]
Maybe related to the image size of your own data

**Comment by lcc157** [comment]
So，how to test own data?

**Comment by BinZhu-ece** [comment]
> So，how to test own data?
I also want to know it.

**Comment by weihaosky** [comment]
It can be directly used on your own data. But you need to fix the bug.

**Comment by BinZhu-ece** [comment]
What I want to know is how to fix the bug, thank you!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Weihao ***@***.***&gt;; 
发送时间: 2022年8月9日(星期二) 上午10:42
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [aliyun/NeWCRFs] RuntimeError: shape &#39;[1, 20, 7, 35, 7, 256]&#39; is invalid for input of size 8843520 (Issue #4)





 
It can be directly used on your own data. But you need to fix the bug.

**Comment by 754467737** [comment]
> 
The reason for the error is that your image H,W is not divisible by 32 during the network downsampling process. you can refer to the yolo-v5--def letterbox  to change the H,W to be divisible by 32.

**Comment by 6leet** [comment]
Hi, I'm facing this problem currently, is there any general solution yet? Thanks!

**Comment by Ericchen328** [comment]
is there any solution to this problem
