### ISSUE TITLE
RuntimeError: shape '[1, 20, 7, 35, 7, 256]' is invalid for input of size 8843520

### ISSUE THREAD

**Issue by Ericchen328** [aliyun/NeWCRFs#51]
I use my own data as the train dataset and there is a bug 
![image](https://github.com/aliyun/NeWCRFs/assets/94337796/9035ed11-0485-4d91-9c20-5fa225eeb1bf)

**Comment by LWW-coder** [comment]
i have the same question  do you have any solutions
