### ISSUE TITLE
Model weights on panoramic image training

### ISSUE THREAD

**Issue by PeriJuani** [aliyun/NeWCRFs#9]
Hi!

Congratulations on your work!

Will you release the model weights for the panoramic images/training code for it?

Besides, in the paper you mention that you also tried to train the model with 50k images and then fine tune it with the Matterport 3D dataset. Did you obtain those 50k real world images using the Matterport camera?

Thanks in advance!

**Comment by weihaosky** [comment]
For now, we do not have a plan for that, since this model is used in real-world applications. We obtained the images with our own camera.
